baseURL = "http://amadamala.com/"
languageCode = "en-us"
title = "Anil Madamala"
theme = "hyde"

[params]
  description = "I’m a developer with 10 years of expericence in building scalable web applicaitons using Java and cloud services. You can reach me at amadamala@gmail.com"
  author = "Anil Madamala"